# Generated by Django 5.0.6 on 2024-06-30 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.ManyToManyField(blank=True, to='account.account')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_card_sets', models.IntegerField(default=0)),
                ('streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('stats_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='stats',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.accstats'),
        ),
    ]
