# Generated by Django 5.0.6 on 2024-08-05 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.RemoveField(
            model_name='accstats',
            name='streak',
        ),
    ]
