# Generated by Django 5.0.6 on 2024-08-05 15:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_vocabulary_remove_accstats_streak'),
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('language', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='card',
            old_name='title',
            new_name='pos',
        ),
        migrations.AddField(
            model_name='card',
            name='definition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='frequency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='pronunciation',
            field=models.FileField(blank=True, null=True, upload_to='pronunciations/'),
        ),
        migrations.AddField(
            model_name='card',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='target',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('private', models.BooleanField(default=False)),
                ('card_data', models.ManyToManyField(blank=True, null=True, to='cards.card')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_card_sets', to='account.account')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.language')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='target_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.language'),
        ),
        migrations.AlterUniqueTogether(
            name='card',
            unique_together={('source', 'target', 'target_language')},
        ),
        migrations.RemoveField(
            model_name='card',
            name='data',
        ),
    ]
