# Generated by Django 5.0.6 on 2024-08-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_language_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardset',
            name='card_data',
            field=models.ManyToManyField(blank=True, to='cards.card'),
        ),
    ]
